"""Job Indexes

Revision ID: 2aa88e70f465
Revises: e80a0e357ec5
Create Date: 2025-11-29 14:15:36.837777
"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2aa88e70f465"
down_revision: Union[str, Sequence[str], None] = "e80a0e357ec5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_is_done"), table_name="jobs")
    op.drop_index(op.f("ix_job_parent_job_id"), table_name="jobs")
    op.create_index("ix_jobs_depends_on", "jobs", ["depends_on", "is_done"], unique=False)
    op.create_index("ix_jobs_is_done", "jobs", ["is_done"], unique=False)
    op.create_index("ix_jobs_ordering", "jobs", ["priority", "user_id", "updated_at"], unique=False)
    op.create_index("ix_jobs_parent_job_id", "jobs", ["parent_job_id"], unique=False)
    op.create_index("ix_jobs_scheduler", "jobs", ["status", "done", "type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_jobs_scheduler", table_name="jobs")
    op.drop_index("ix_jobs_parent_job_id", table_name="jobs")
    op.drop_index("ix_jobs_ordering", table_name="jobs")
    op.drop_index("ix_jobs_is_done", table_name="jobs")
    op.drop_index("ix_jobs_depends_on", table_name="jobs")
    op.create_index(op.f("ix_job_parent_job_id"), "jobs", ["parent_job_id"], unique=False)
    op.create_index(op.f("ix_job_is_done"), "jobs", ["id", "is_done"], unique=False)
    # ### end Alembic commands ###
